# Site settings
title: Foxtail Website
email: foxtailcreates@gmail.com
description: Foxtail creates online tools for custom florals. Our tools simplify the process of ordering personalized flowers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://foxtailcreates.com/" # the base hostname & protocol for your site

twitter_username:
instagram_username: foxtailcreates

# Build settings
markdown: kramdown
